import type { Metadata } from "next";
import { Lato } from "next/font/google";
import PrelineScriptWrapper from "./components/PrelineScriptWrapper";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Angel Surf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        {children}
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}
